#!/bin/bash

main() {

  install_whl

  if [[ -f /etc/ComunioScore/cfg.ini ]]
  then
      echo "Start Application ComunioScore"
      enable_service_file
      stop_service_file
      start_service_file
  else
      echo "ComunioScore not started due to missing configuration file!"
  fi

}

install_whl() {

  echo "Install ComunioScore Application"
  pip3 install /etc/ComunioScore/ComunioScore-*-py3-none-any.whl

}

enable_service_file() {

  echo "Enable ComunioScore.service file"
  systemctl enable ComunioScore.service

}

stop_service_file() {

  echo "Stop ComunioScore.service file"
  systemctl stop ComunioScore.service

}

start_service_file() {

  echo "Start ComunioScore.service file"
  systemctl start ComunioScore.service

}

main
