sudo: required
language: python
python:
  - "3.6"   # development interpreter

# install dependencies
install:
  - pip3 install -r requirements.txt

script:
  - python3 -m unittest discover ComunioScore/test/